# monitoring/helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
# monitoring/loki-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: latest
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  
  # Кастомные values
  values:
    # Встроенные values
    fullnameOverride: loki
    
    # Базовая конфигурация
    config:
      auth_enabled: false
  
  # Ссылка на external values
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
