# monitoring/promtail-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.15.x"  # Укажите нужную версию
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  
  values:
    fullnameOverride: promtail
    
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
  
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values
      valuesKey: values.yaml
