# infrastructure/helmcharts/promtail-values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-values
data:
  values.yaml: |
    config:
      snippets:
        extraScrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: 
                  [__meta_kubernetes_pod_annotation_logs_grafana_com_scrape]
                action: keep
                regex: true
