---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring                                                                                       
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      namespace: monitoring
      name: loki-values