---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: ">= 5.0.0 < 6.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
  values: |
    loki:
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /loki/index
          cache_location: /loki/index_cache
          resync_interval: 5s
          shared_store: s3
        aws:
          s3:
            endpoint: http://minio:9000
            region: eu-west-2
            bucketnames: aws-loki-dev
            s3forcepathstyle: true
            insecure: true
            access_key_id: minioadmin
            secret_access_key: minioadmin
      pattern_ingester:
          enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 672h
      storage:
        type: s3
        bucketNames:
            chunks: aws-loki-chunk
            ruler: aws-loki-dev-ruler
            admin: aws-loki-dev-admin
        s3:
          endpoint: http://minio:9000
          region: eu-west-2
          secretAccessKey: minioadmin
          accessKeyId: minioadmin
          s3ForcePathStyle: true
          insecure: true
          http_config: {}
      compactor:
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        working_directory: /loki/compactor
        shared_store: s3
    minio:
      enabled: false
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0