---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring                                                                                    
      interval: 1m
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage_config: 
        aws:
          region: eu-west-2
          bucketnames: aws-loki-dev-chunk
          s3forcepathstyle: true
      pattern_ingester:
          enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 672h
      storage:
        type: s3
        bucketNames:
            chunks: aws-loki-dev-chunk
            ruler: aws-loki-dev-ruler
            admin: aws-loki-dev-admin
        s3:
          endpoint: http://minio:9000
          region: eu-west-2
          secretAccessKey: minioadmin
          accessKeyId: minioadmin
          s3ForcePathStyle: true
          insecure: true
          http_config: {}
      compactor:
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: s3
    minio:
      enabled: false
    deploymentMode: SimpleScalable
    backend:
      replicas: 1
    read:
      replicas: 1
    write:
      replicas: 1
---
apiVersion: v1
data:
  datasource.yaml: "apiVersion: 1\ndatasources: \n  - access: proxy\n    isDefault:
    true\n    name: VictoriaMetrics\n    type: prometheus\n    url: http://vmsingle-vmks-victoria-metrics-k8s-stack.monitoring.svc.cluster.local.:8429\n
    \ - access: proxy\n    jsonData:\n      implementation: prometheus\n    name:
    Alertmanager\n    type: alertmanager\n    url: http://vmalertmanager-vmks-victoria-metrics-k8s-stack.monitoring.svc.cluster.local.:9093"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: vmks
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-03-01T17:21:26Z"
  labels:
    app: victoria-metrics-k8s-stack-grafana
    app.kubernetes.io/instance: vmks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/version: v1.113.0
    grafana_datasource: "1"
    helm.sh/chart: victoria-metrics-k8s-stack-0.39.0
    helm.toolkit.fluxcd.io/name: vmks
    helm.toolkit.fluxcd.io/namespace: monitoring
  name: vmks-victoria-metrics-k8s-stack-grafana-dsssss
  namespace: monitoring
  resourceVersion: "49772404"
  uid: 684f7c3a-e325-4fd0-bdd8-dbef4398e3fc
