---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring                                                                                    
      interval: 1m
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push